### ISSUE TITLE
[Bug] Typing Chinese (IME on) after a virtual link at the beginning of a sentence can cause display errors.

### ISSUE THREAD

**Issue by Yaozhuwa** [vschroeter/obsidian-virtual-linker#12]
Thanks for your amazing work! It helps a lot!

Typing Chinese (IME on) after a virtual link at the beginning of a sentence can cause display errors.

https://github.com/vschroeter/obsidian-virtual-linker/assets/28787183/4b4cd335-8f28-4c75-bb5a-c27d1cf6d2ed

This situation also occurs at the beginning of a list and a quote.
<img width="1512" alt="image" src="https://github.com/vschroeter/obsidian-virtual-linker/assets/28787183/1e05fd7f-116b-4f0c-802d-e6d2df9f1305">

<img width="1365" alt="image" src="https://github.com/vschroeter/obsidian-virtual-linker/assets/28787183/fa5ffb8b-5936-41ab-b1e4-3ec9b191f44b">

This situation does not occur when it is in the middle of a sentence.

https://github.com/vschroeter/obsidian-virtual-linker/assets/28787183/74811e87-2767-4168-9fec-345dcb05e8bd

**Comment by vschroeter** [comment]
Good news: I could reproduce it.
Not so good news: This is nothing I can directly avoid, as it is caused by IME on top of the plugin.

Maybe good news: I've added a setting to disable linking for the current line you're typing in. 
This should avoid this problem.

You can test it in [Version 1.3.6](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.3.6)
